[General]
include = default.conf

[Rule]
DOMAIN-SUFFIX,tigerfintech.com,PROXY
DOMAIN-SUFFIX,laohu8.com,PROXY
DOMAIN-SUFFIX,tradeup.com,PROXY
DOMAIN-SUFFIX,tigerfintech.com,PROXY
DOMAIN-SUFFIX,skytigris.cn,PROXY
DOMAIN-SUFFIX,tigerbbs.com,PROXY
